name: Create image and Deploy

env:
  IMAGE_TAG: 3.8.18

on:
  push: {}
  repository_dispatch:
    types: [run]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t acdhch/bibsonomy .
      - name: docker push to dockerhub
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" 
          docker push acdhch/bibsonomy:${{ env.IMAGE_TAG }}
      - name: login to github container registry 
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker push to github container registry   
        run: |
          docker push ghcr.io/acdh-oeaw/bibsonomy:{{ env.IMAGE_TAG }} 
          
  rancher:
     needs: push_to_registry
     name: Deploy to rancher
     runs-on: ubuntu-latest
     steps:
     - name: Rancher Deploy Action
       run: |
          curl -i -X POST "${{ secrets.RANCHERURL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHER_BARER_TOKEN }}"
